#!/bin/bash
# NOTE: This script is generated by Claude Code.


# ════════════════════════════════════════════════════════════
# ════════════ Install script for Ubuntu or MacOS ════════════
# ════════════════════════════════════════════════════════════

# Usage:
#   curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash
#   curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash -s -- --help

set -e


# ════════════════════════ Constants ═════════════════════════

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DOTFILE_PATH="${DOTFILE_PATH:-$([[ "$(uname)" == 'Darwin' ]] && echo "$HOME/Documents/Fau/dotfiles" || echo "$XDG_CONFIG_HOME/dotfiles")}"
REPO_URL="https://github.com/Fau818/dotfiles.git"


# ═════════════════════ Helper Functions ═════════════════════

__info()  { echo -e "\033[1;34m[INFO]\033[0m $1"; }
__ok()    { echo -e "\033[1;32m[OK]\033[0m $1"; }
__warn()  { echo -e "\033[1;33m[WARN]\033[0m $1"; }
__error() { echo -e "\033[1;31m[ERROR]\033[0m $1"; }

# Install packages with the platform package manager
__install() {
  if [[ "$(uname)" == 'Darwin' ]]; then
    command -v brew &> /dev/null || { __error "Homebrew is not installed, see https://brew.sh"; return 1; }
    brew install "$@"
  else
    sudo apt-get update -qq && sudo apt-get install -y "$@"
  fi
}

# Ensure the given commands exist, installing the missing ones in one shot
__ensure() {
  local cmd missing=()
  for cmd in "$@"; do
    command -v "$cmd" &> /dev/null || missing+=("$cmd")
  done
  (( ${#missing[@]} == 0 )) && return 0

  __info "Installing ${missing[*]}..."
  __install "${missing[@]}" || { __error "Failed to install ${missing[*]}!"; return 1; }
  for cmd in "${missing[@]}"; do
    command -v "$cmd" &> /dev/null || { __error "Failed to install $cmd!"; return 1; }
  done
  __ok "${missing[*]} installed successfully."
}


# ══════════════════════ Dotfile Puller ══════════════════════

__dotfile_pull() {
  if [[ -e "$DOTFILE_PATH" ]]; then
    __warn "Dotfiles already exist at $DOTFILE_PATH, skipping clone."
  else
    __ensure git
    __info "Cloning dotfiles to $DOTFILE_PATH..."
    git clone --depth 1 "$REPO_URL" "$DOTFILE_PATH"
    __ok "Dotfiles cloned successfully."
  fi
}


# ═════════════════════════ ZSH Init ═════════════════════════

__zsh_init() {
  __ensure zsh stow

  # IMPO: Pre-create `~/.config`, otherwise stow folds it into a single symlink
  mkdir -p "$HOME/.config"

  __info "Stowing zsh configuration..."
  if ! stow --dir="$DOTFILE_PATH" --target="$HOME" --ignore='.DS_Store' zsh; then
    __error "Failed to stow zsh! Back up the conflicting files listed above, then re-run this script."
    return 1
  fi
  __ok "Zsh configuration installed. Restart your shell or run: exec zsh"
}


# ════════════════════════ Main Entry ════════════════════════

__show_help() {
  cat << 'EOF'
Fau's Dotfiles Installer

Usage:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash
  ./starter.sh [OPTIONS]

Options:
  --help, -h      Show this help message
  --zsh           Clone dotfiles and setup zsh configuration (default when no args)
  --pull          Clone dotfiles repository only

Environment:
  DOTFILE_PATH    Clone destination
                  (default: ~/Documents/Fau/dotfiles on macOS, $XDG_CONFIG_HOME/dotfiles on Linux)

Examples:
  # One-liner to setup zsh on a new machine:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash

  # Clone dotfiles only:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash -s -- --pull
EOF
}

main() {
  local action="${1:---zsh}"

  case "$action" in
    --help|-h)
      __show_help
      ;;
    --pull)
      __dotfile_pull
      ;;
    --zsh)
      __dotfile_pull
      __zsh_init
      ;;
    *)
      __error "Unknown option: $action"
      __show_help
      exit 1
      ;;
  esac
}

# Run main if script is executed (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] || [[ -z "${BASH_SOURCE[0]}" ]]; then
  main "$@"
fi
