#!/bin/bash
# NOTE: This script is generated by Claude Code.

# ****************************************************************************
# ******************** Install script for Ubuntu or MacOS ********************
# ****************************************************************************
# Usage:
#   curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash
#   curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash -s -- --help
# ****************************************************************************

set -e

# -----------------------------------
# -------- Constants
# -----------------------------------
DOTFILE_PATH=$([[ "$(uname)" == 'Darwin' ]] && echo "$HOME/Documents/Fau/dotfiles" || echo "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles")
REPO_URL="https://github.com/Fau818/dotfiles.git"


# -----------------------------------
# -------- Helper Functions
# -----------------------------------
__info()  { echo -e "\033[1;34m[INFO]\033[0m $1"; }
__ok()    { echo -e "\033[1;32m[OK]\033[0m $1"; }
__warn()  { echo -e "\033[1;33m[WARN]\033[0m $1"; }
__error() { echo -e "\033[1;31m[ERROR]\033[0m $1"; }


# -----------------------------------
# -------- Dotfile Puller
# -----------------------------------
__dotfile_pull() {
  if [[ -e "$DOTFILE_PATH" ]]; then
    __warn "Dotfiles already exist at $DOTFILE_PATH, skipping clone."
  else
    __info "Cloning dotfiles to $DOTFILE_PATH..."
    git clone --depth 1 "$REPO_URL" "$DOTFILE_PATH"
    __ok "Dotfiles cloned successfully."
  fi
}


# -----------------------------------
# -------- ZSH Init
# -----------------------------------
__zsh_init() {
  # Detect stow
  if ! command -v stow &> /dev/null; then
    __error "stow command not found! Please install stow first."
    __info "  macOS: brew install stow"
    __info "  Ubuntu: sudo apt install stow"
    return 1
  fi

  __info "Stowing zsh configuration..."
  stow --dir="$DOTFILE_PATH" --target="$HOME" --ignore='.DS_Store' zsh
  __ok "Zsh configuration installed. Restart your shell or run: exec zsh"
}


# -----------------------------------
# -------- Main Entry
# -----------------------------------
__show_help() {
  cat << 'EOF'
Fau's Dotfiles Installer

Usage:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash
  ./starter.sh [OPTIONS]

Options:
  --help, -h      Show this help message
  --zsh           Setup zsh configuration only (default when no args)
  --pull          Clone dotfiles repository only

Examples:
  # One-liner to setup zsh on a new machine:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash

  # Clone dotfiles only:
  curl -sSL https://raw.githubusercontent.com/Fau818/dotfiles/main/starter.sh | bash -s -- --pull
EOF
}

main() {
  local action="${1:---zsh}"

  case "$action" in
    --help|-h)
      __show_help
      ;;
    --pull)
      __dotfile_pull
      ;;
    --zsh)
      __dotfile_pull
      __zsh_init
      ;;
    *)
      __error "Unknown option: $action"
      __show_help
      exit 1
      ;;
  esac
}

# Run main if script is executed (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] || [[ -z "${BASH_SOURCE[0]}" ]]; then
  main "$@"
fi
