# ==================== Preview ====================
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "<C-p>"
run  = "plugin hide-preview"
desc = "Hide or show preview"


# ==================== Smart Paste ====================
[[manager.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"


# ==================== Smart Move ====================
[[manager.prepend_keymap]]
on  = "k"
run = "plugin arrow --args=-1"
[[manager.prepend_keymap]]
on  = "j"
run = "plugin arrow --args=1"

# [[manager.prepend_keymap]]
# on  = "K"
# run = "plugin parent-arrow --args=-1"
# [[manager.prepend_keymap]]
# on  = "J"
# run = "plugin parent-arrow --args=1"


# ==================== Smart Tab ====================
[[manager.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on  = [ "<Up>" ]
run = "plugin --sync parent-arrow --args=-1"
[[manager.prepend_keymap]]
on  = [ "<Down>" ]
run = "plugin --sync parent-arrow --args=1"


[[manager.prepend_keymap]]
on   = "F"
run  = "plugin jump-to-char"
desc = "Jump to char"



# ==================== TEST ====================
# [[manager.prepend_keymap]]
# on   = "l"
# run  = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"
# [[manager.prepend_keymap]]
# on   = "2"
# run  = "plugin smart-switch --args=1"
# desc = "Switch or create tab 2"
