# =============================================
# ======== Custom Keymaps
# =============================================
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"


[[manager.prepend_keymap]]
on   = [ "p" ]
run  = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"


[[manager.prepend_keymap]]
on   = "<C-p>"
run  = "plugin --sync hide-preview"
desc = "Hide or show preview"


[[manager.prepend_keymap]]
on   = "F"
run  = "plugin jump-to-char"
desc = "Jump to char"


[[manager.prepend_keymap]]
on  = [ "k" ]
run = "plugin --sync arrow --args=-1"
[[manager.prepend_keymap]]
on  = [ "j" ]
run = "plugin --sync arrow --args=1"
# [[manager.prepend_keymap]]
# on  = [ "K" ]
# run = "plugin --sync arrow --args=-5"
# [[manager.prepend_keymap]]
# on  = [ "J" ]
# run = "plugin --sync arrow --args=5"


[[manager.prepend_keymap]]
on  = [ "<Up>" ]
run = "plugin --sync parent-arrow --args=-1"
[[manager.prepend_keymap]]
on  = [ "<Down>" ]
run = "plugin --sync parent-arrow --args=1"
