# ==================== Fuzzy Finder (Swaped zoxide and fzf default keymappings) ====================
[[mgr.prepend_keymap]]
on  = "z"
run = "plugin zoxide"

[[mgr.prepend_keymap]]
on  = "Z"
run = "plugin fzf"


# ==================== Quick Move ====================
[[mgr.prepend_keymap]]
on  = "K"
run = "plugin arrow -3"

[[mgr.prepend_keymap]]
on  = "J"
run = "plugin arrow 3"


# ==================== Preview ====================
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"


# ==================== Smart Paste ====================
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"


# ==================== Smart Tab ====================
[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on  = [ "<Up>" ]
run = "plugin --sync parent-arrow -1"
[[mgr.prepend_keymap]]
on  = [ "<Down>" ]
run = "plugin --sync parent-arrow 1"


[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin jump-to-char"
desc = "Jump to char"


# ==================== Preview ====================
[[mgr.prepend_keymap]]
on = "<Space>"
run = 'shell -- qlmanage -p "$@"'
