#  WARN: This script is fully generated by Claude Code.
# =============================================
# ======== Conda Auto-Env
# =============================================
# Auto-activate a conda env when entering a mapped directory (or any of its
# subdirectories); deactivate on leave. Manually-activated envs are never
# overridden. The conda subprocess (~200ms) runs in the background, so `cd`
# is never blocked; the result is applied at the next prompt/command.
#
# Patterns may contain globs; the longest matching pattern wins.
typeset -gA CONDA_AUTO_ENVS=(
  "$HOME/Documents/Fau/projects/school/eece5644"  eece5644
)

[[ -n "${CONDA_EXE-}" ]] || return 0  # needs conda.sh sourced first (python.zsh)

typeset -gi _CAE_GEN=0 _CAE_TICKS=0
typeset -gi _CAE_MAX_TICKS=5  # give up after this many 1s timer ticks
typeset -g  _CAE_ACTIVE=''   # env we auto-activated ('' = not managing any)
typeset -g  _CAE_INTENT='' _CAE_FROM=''
typeset -g  _CAE_PENDING=''  # result file of the in-flight switch
typeset -g  _CAE_PID=''      # pid of the in-flight conda subprocess
typeset -g  _CAE_TMP="${TMPDIR:-/tmp}/conda_auto_env.$$"
typeset -g  _CAE_ARMED='' _CAE_TMOUT_SAVE='' _CAE_TRAP_SAVE=''

# While a switch is in flight, a 1s alarm ticks until the result lands, so an
# idle prompt refreshes without a keypress; disarmed (state restored) once
# settled. Only these timer ticks count toward the timeout.
_cae_arm() {
  [[ -n "$_CAE_ARMED" ]] && return 0
  _CAE_ARMED=1
  _CAE_TMOUT_SAVE=${TMOUT-}
  _CAE_TRAP_SAVE=${functions[TRAPALRM]-}
  TMOUT=1
  TRAPALRM() { _cae_tick }
}

_cae_tick() {
  _cae_pump
  [[ -n "$_CAE_PENDING" ]] || return 0  # applied or discarded -> done
  if (( ++_CAE_TICKS >= _CAE_MAX_TICKS )); then
    print -ru2 -- "conda_auto_env: '${_CAE_INTENT:-deactivate}' did not finish after ${_CAE_MAX_TICKS}s; giving up"
    [[ -n "$_CAE_PID" ]] && kill "$_CAE_PID" 2>/dev/null
    command rm -f -- "$_CAE_PENDING" "$_CAE_PENDING.wip" 2>/dev/null
    _CAE_PENDING=''
    _cae_disarm
    zle && zle reset-prompt
  fi
}

_cae_disarm() {
  [[ -n "$_CAE_ARMED" ]] || return 0
  _CAE_ARMED=''
  if [[ -n "$_CAE_TMOUT_SAVE" ]]; then TMOUT=$_CAE_TMOUT_SAVE; else unset TMOUT; fi
  if [[ -n "$_CAE_TRAP_SAVE" ]]; then functions[TRAPALRM]=$_CAE_TRAP_SAVE; else unfunction TRAPALRM 2>/dev/null; fi
}

# $REPLY = env mapped to the longest pattern matching $PWD, or ''
_cae_lookup() {
  local pat best=''
  REPLY=''
  for pat in "${(@k)CONDA_AUTO_ENVS}"; do
    [[ "$PWD" == ${~pat} || "$PWD" == ${~pat}/* ]] || continue
    (( ${#pat} > ${#best} )) && best=$pat
  done
  [[ -n "$best" ]] && REPLY="${CONDA_AUTO_ENVS[$best]}"
}

# Apply a finished background switch, unless the world moved on while it ran
# (cwd no longer wants it, or the env was changed manually in the meantime).
_cae_pump() {
  if [[ -z "$_CAE_PENDING" ]]; then _cae_disarm; return 0; fi
  [[ -e "$_CAE_PENDING" ]] || return 0  # still running; stay armed
  local file=$_CAE_PENDING out REPLY
  _CAE_PENDING=''
  _cae_disarm
  out="$(<$file)"
  command rm -f -- "$file"
  _cae_lookup
  [[ "$REPLY" == "$_CAE_INTENT" && "${CONDA_DEFAULT_ENV-}" == "$_CAE_FROM" ]] || return 0
  if [[ -z "$out" ]]; then
    print -ru2 -- "conda_auto_env: env switch failed (check env names in CONDA_AUTO_ENVS)"
    return 1
  fi
  local saved_ps1=$PS1  # conda's output overwrites PS1; keep the real prompt
  eval "$out"
  PS1=$saved_ps1
  rehash
  _CAE_ACTIVE=$_CAE_INTENT
  _cae_refresh
  return 0
}

# Repaint an idle prompt. p10k caches segment text at precmd, so a bare
# reset-prompt would redraw stale content; recompute via its precmd first.
_cae_refresh() {
  zle || return 0
  (( ${+functions[_p9k_precmd]} )) && _p9k_precmd
  zle reset-prompt
}

# _cae_dispatch <target-env|''> <shell.posix args...>
_cae_dispatch() {
  setopt localoptions nonotify nomonitor
  (( _CAE_GEN++ ))
  _CAE_INTENT=$1
  _CAE_FROM="${CONDA_DEFAULT_ENV-}"
  shift
  if [[ -o interactive ]]; then
    [[ -n "$_CAE_PENDING" ]] && command rm -f -- "$_CAE_PENDING"
    [[ -n "$_CAE_PID" ]] && kill "$_CAE_PID" 2>/dev/null
    local out="$_CAE_TMP.$_CAE_GEN"
    _CAE_PENDING=$out
    _CAE_TICKS=0
    { "$CONDA_EXE" shell.posix "$@" > "$out.wip" 2>/dev/null && command mv -f -- "$out.wip" "$out" } &!
    _CAE_PID=$!
    _cae_arm
  else
    local out
    out="$("$CONDA_EXE" shell.posix "$@" 2>/dev/null)"
    [[ -n "$out" ]] && eval "$out" && rehash && _CAE_ACTIVE=$_CAE_INTENT
  fi
}

_cae_chpwd() {
  _cae_pump  # settle any in-flight switch before deciding
  local REPLY cur="${CONDA_DEFAULT_ENV-}"
  _cae_lookup
  if [[ -n "$REPLY" ]]; then
    [[ "$cur" == "$REPLY" ]] && return 0
    if [[ -z "$cur" || "$cur" == base || "$cur" == "$_CAE_ACTIVE" ]]; then
      _cae_dispatch "$REPLY" activate "$REPLY"
    fi
  elif [[ -n "$_CAE_ACTIVE" ]]; then
    if [[ "$cur" == "$_CAE_ACTIVE" ]]; then
      _cae_dispatch '' deactivate
    else
      _CAE_ACTIVE=''
    fi
  fi
}

_cae_cleanup() { command rm -f -- $_CAE_TMP.*(N) }

autoload -Uz add-zsh-hook
add-zsh-hook chpwd   _cae_chpwd
add-zsh-hook precmd  _cae_pump
add-zsh-hook preexec _cae_pump
add-zsh-hook zshexit _cae_cleanup
_cae_chpwd  # cover shells that start inside a mapped directory
